services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development

volumes:
  node_modules:
