services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
