services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
